version: '3.8'
services:
  strapidb:
    container_name: strapidb
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Letmein!
    ports:
      - '5432:5432'
    volumes:
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    expose:
      - '5432'
    networks:
      - strapinet
  strapi:
    container_name: strapi
    image: strapi/strapi
    restart: always
    depends_on:
      - strapidb
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: strapi
      DATABASE_HOST: host.docker.internal
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: Letmein!
    ports:
      - '1337:1337'
    volumes:
      - ./app:/srv/app
    networks:
      - strapinet

networks:
  strapinet: